# Site settings
title: Joshua Anthony
email: f/xyylrwgk
url: https://shadowsora211.github.io/
description: "アンソニー・ジョシュアのゲーム開発ポートフォリオサイト。プロジェクトの紹介やお問い合わせはこちらをご覧ください！"
keywords: "Game dev, game programmer, pixel art, 8bit, VR, AR, virtual reality"
skills: "ゲームプログラマー"
meta_author: Anthony Joshua

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: EF476F #80B3FF
  primary-rgb: "239,71,111" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Joshua Anthony
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/joshua-anthony-807621a7/
  - title: stack-overflow
    url: https://stackoverflow.com/users/6584553/shadowsora
  - title: github
    url: https://github.com/shadowsora211

# Postal address (add as many lines as necessary)
address:
  - line: 埼玉県
  - line: 日本

# Credits content
credits: 'Website created with the <a href="https://github.com/jeromelachaud/freelancer-theme">Freelancer Jekyll theme</a>'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
